name: ✅ Task Implementation
description: Implement a specific task or improvement
title: "[Task] "
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template for implementing specific tasks or improvements.

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be implemented?
      placeholder: Clearly describe the task
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List specific, testable requirements
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: Technical Approach
      description: How should this be implemented?
      placeholder: Outline the implementation strategy

  - type: checkboxes
    id: checklist
    attributes:
      label: Implementation Checklist
      options:
        - label: Code implementation
        - label: Unit tests
        - label: Integration tests
        - label: Documentation update
        - label: UI/UX updates
